# Static Configuration File - INTEGRATED OPTIONS ONLY
# These settings require server restart to take effect
# For dynamic AI model settings, use runtime_config.yaml

# Gateway configuration (WebSocket server settings)
gateway:
  host: "127.0.0.1"              # Server bind address - ✅ INTEGRATED
  port: 8000                     # Server port - ✅ INTEGRATED
  connection_timeout: 300        # Connection timeout in seconds - ✅ INTEGRATED
  max_upload_size: 52428800      # Maximum upload size in bytes - ✅ READY TO USE

# Router configuration (request handling)
router:
  request_timeout: 60            # Request timeout in seconds - ✅ INTEGRATED
  max_retries: 3                 # Maximum retry attempts - ✅ INTEGRATED

# MCP service configuration
mcp:
  database_path: "mcp.db"        # SQLite database path - ✅ DEFINED
  redis_url: null                # Redis URL for pub/sub - ✅ DEFINED
  enable_tool_parameter_validation: false  # Enable tool parameter validation and type checking - ✅ READY TO USE

# Logging configuration
logging:
  level: "INFO"                    # Log level - ✅ INTEGRATED
  enable_pretty_print: false      # Custom pretty print for debugging - ✅ INTEGRATED
  enable_jq_json_formatting: false  # jq-style JSON formatting - ✅ INTEGRATED
  save_to_file: true               # Save logs to file - ✅ READY TO USE
  log_file_path: "server.log"     # Log file path (relative to root) - ✅ READY TO USE
  max_log_file_size: 10485760     # Max log file size in bytes (10MB) - ✅ READY TO USE
  backup_count: 5                 # Number of backup log files to keep - ✅ READY TO USE
  log_tool_calls_only: true       # When true, ONLY log tool call JSON (suppresses all other logs) - ✅ READY TO USE
