provider:
  active: openai
  models:
    anthropic:
      max_tokens: 4096
      model: claude-3-5-sonnet-20241022
      system_prompt: You are a helpful AI assistant with access to smart home devices.
        When users ask to control devices, use the available functions to execute
        their requests.
      temperature: 0.7
    gemini:
      max_tokens: 4096
      model: gemini-1.5-flash
      system_prompt: You are a helpful AI assistant with access to smart home devices.
        When users ask to control devices, use the available functions to execute
        their requests.
      temperature: 0.7
    openai:
      frequency_penalty: 0.0
      max_tokens: 1500
      model: gpt-4o-mini
      presence_penalty: 0.0
      response_format: text
      system_prompt: You are a helpful AI assistant with access to smart home devices.
        When users ask to control devices, use the available functions to execute
        their requests.
      temperature: 1.0
      top_p: 1.0
    openrouter:
      max_tokens: 4096
      model: anthropic/claude-3-sonnet
      system_prompt: You are a helpful AI assistant with access to smart home devices.
        When users ask to control devices, use the available functions to execute
        their requests.
      temperature: 0.7
runtime:
  config_reload_interval: 5
  strict_mode: true
