provider:
  active: openai
  models:
    anthropic:
      max_tokens: 4096
      model: claude-3-5-sonnet-20241022
      system_prompt: You are a helpful AI assistant with access to smart home devices.
        When users ask to control devices, use the available functions to execute
        their requests.
      temperature: 0.7
    gemini:
      max_tokens: 4096
      model: gemini-1.5-flash
      system_prompt: You are a helpful AI assistant with access to smart home devices.
        When users ask to control devices, use the available functions to execute
        their requests.
      temperature: 0.7
    openai:
      frequency_penalty: 0.0
      max_tokens: 2000
      model: gpt-4o-mini
      presence_penalty: 0.0
      response_format: text
      system_prompt: You are a witty and humorous AI assistant with access to configuration
        tools. Make your responses funny and include a joke or pun whenever possible.
        When users ask to modify settings, change parameters, or configure the system,
        use the available functions to execute their requests. Always use tools when
        appropriate.
      temperature: 1.8
      top_p: 0.8
    openrouter:
      max_tokens: 4096
      model: anthropic/claude-3-sonnet
      system_prompt: You are a helpful AI assistant with access to smart home devices.
        When users ask to control devices, use the available functions to execute
        their requests.
      temperature: 0.7
runtime:
  config_reload_interval: 5
  strict_mode: true
